### ISSUE TITLE
Multiple Check commands with Shell commands before and timeout

### ISSUE THREAD

**Issue by tiborschneider** [pulp-platform/plptest#2]
There seems to be a problem when using multiple `Check` commands with `Shell` commands in between, and when `timeout` is set. The following `testset.cfg` reproduces the error:

```python
from plptest import Testset, Test, Shell, Check

def check(config, output, obj):
    for line in output.splitlines():
        if line.startswith("__"):
            print(line[2:])
    return (1, obj)

TestConfig = {
  "testsets": [
    Testset(
      name  = 'set',
      tests = [
        Test(
          name = 'test',
          commands = [
            Shell("S1", "echo __S1"),
            Check("C1", check, "__C1\n"),
            Check("C2", check, "__C2\n"),
          ],
          timeout=20,
        )
      ],
    )
  ]
}
```

The expected result (when calling `plptest --stdout`) is:
```
START set:test      wolfe
S1
S1
C1
OK:   set:test      wolfe

+----------+--------+----------+--------------+
| test     | config |   time   | passed/total |
+----------+--------+----------+--------------+
| set      |        |   0.01   |     1/1      |
| set:test | wolfe  | 0.008753 |     1/1      |
+----------+--------+----------+--------------+
```

However, the actual response is:
```
S1
unexpected error in processEnded
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/process.py", line 63, in reapAllProcesses
    process.reapProcess()
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/process.py", line 311, in reapProcess
    self.processEnded(status)
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/_baseprocess.py", line 52, in processEnded
    self.maybeCallProcessEnded()
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/process.py", line 1097, in maybeCallProcessEnded
    _BaseProcess.maybeCallProcessEnded(self)
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/_baseprocess.py", line 64, in maybeCallProcessEnded
    proto.processEnded(Failure(reason))
  File "/home/pulp/pulp/pulp-sdk/pkg/sdk/dev/install/ws/python/plptest_utils.py", line 438, in processEnded
    self.handle_cmd_end()
  File "/home/pulp/pulp/pulp-sdk/pkg/sdk/dev/install/ws/python/plptest_utils.py", line 428, in handle_cmd_end
    self.runCommand()
  File "/home/pulp/pulp/pulp-sdk/pkg/sdk/dev/install/ws/python/plptest_utils.py", line 563, in runCommand
    self.handle_cmd_end()
  File "/home/pulp/pulp/pulp-sdk/pkg/sdk/dev/install/ws/python/plptest_utils.py", line 428, in handle_cmd_end
    self.runCommand()
  File "/home/pulp/pulp/pulp-sdk/pkg/sdk/dev/install/ws/python/plptest_utils.py", line 463, in runCommand
    self.timeout_call_id.cancel()
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/base.py", line 97, in cancel
    raise error.AlreadyCancelled
twisted.internet.error.AlreadyCancelled: Tried to cancel an already-cancelled event.
```

The expected result is printed if the `timeout=20` argument is omitted. Also, if no `Shell` command is used, no error does ocurr.

**Comment by tiborschneider** [comment]
commit ecf8dfcea8ebd08e789cb954668cce6ad6e3cd2e fixes the issue. Thanks
